### ISSUE TITLE
Would it be possible for this to work on weaker hardware?

### ISSUE THREAD

**Issue by kunokdev** [9e15/net-9e15-nominatim-docker#1]
Would this instance work on a 12GB RAM/i5/1TB HDD laptop for whole planet data? 
Would you go against setting it up on so much weaker hardware?

**Comment by merlinnot** [comment]
That's definitely possible to run this on even weaker hardware, but it will obviously run slower. The main factor in your configuration would be the HDD, Nominatim makes a massive amount of small reads and writes, especially during the import process. You can check out some benchmarks [here](http://wiki.openstreetmap.org/wiki/Osm2pgsql/benchmarks).
