### ISSUE TITLE
PostGIS error in step 49/68

### ISSUE THREAD

**Issue by sfranchois** [9e15/net-9e15-nominatim-docker#2]
HI, has anyone seen this error before (at end of log)? No other errors encountered before.
I tried twice on a clean Docker droplet :

...
ALTER SYSTEM SET full_page_writes TO 'off';
ALTER SYSTEM
ALTER SYSTEM SET logging_collector TO 'off';
ALTER SYSTEM
 * Stopping PostgreSQL 9.6 database server
   ...done.
 ---> 645a7a0deb5e
Removing intermediate container 18ccc7cca4ea
Step 47/68 : USER root
 ---> Running in 0e348fc8ab02
 ---> 586f64ff0789
Removing intermediate container 0e348fc8ab02
Step 48/68 : ARG OSM2PGSQL_CACHE=24000
 ---> Running in aa3904e144b2
 ---> 7ac49185f394
Removing intermediate container aa3904e144b2
Step 49/68 : RUN service postgresql start &&     sudo -u nominatim ${USERHOME}/Nominatim/build/utils/setup.php       --osm-file /srv/nominatim/src/data.osm.pbf       --all       --threads ${BUILD_THREADS}       --osm2pgsql-cache ${OSM2PGSQL_CACHE} &&     service postgresql stop
 ---> Running in d10f2fa5e72d
 * Starting PostgreSQL 9.6 database server
   ...done.
2018-01-16 10:39:01 == WARNING: resetting threads to 2
2018-01-16 10:39:01 == Create DB
2018-01-16 10:39:03 == Setup DB
Postgres version found: 9.6
pgsql returned with error code (3)
ERROR:  could not access file "$libdir/postgis-2.4": No such file or directory
ERROR: pgsql returned with error code (3)
The command '/bin/sh -c service postgresql start &&     sudo -u nominatim ${USERHOME}/Nominatim/build/utils/setup.php       --osm-file /srv/nominatim/src/data.osm.pbf       --all       --threads ${BUILD_THREADS}       --osm2pgsql-cache ${OSM2PGSQL_CACHE} &&     service postgresql stop' returned a non-zero code: 255

**Comment by merlinnot** [comment]
I think I know where it comes from, I'll try to fix it in an hour or so.

**Comment by merlinnot** [comment]
Fixed via 75930e8afe9806e6ba4cc4e2c1b66df3e7df2ef2

**Comment by alialamine** [comment]
This is happening again. it's 2.5 now. This can be manually overriden with `--build-arg POSTGIS_VERSION=2.5` when building and that would apply to any future version (just change 2.5 to whatever the current version is)
