### ISSUE TITLE
Build Failaure

### ISSUE THREAD

**Issue by devendrasr** [9e15/net-9e15-nominatim-docker#4]
Hi, 
We are getting build failures with below error - 

Reading in file: /srv/nominatim/src/data.osm.pbf
Using PBF parser.
Processing: Node(2727010k 385.4k/s) Way(0k 0.00k/s) Relation(0 0.00/s)Error executing external command: /srv/nominatim/Nominatim/build/osm2pgsql/osm2pgsql -lsc -O gazetteer --hstore --number-processes 1 -C 28000 -P 5432 -d nominatim /srv/nominatim/src/data.osm.pbf
ERROR: Error executing external command: /srv/nominatim/Nominatim/build/osm2pgsql/osm2pgsql -lsc -O gazetteer --hstore --number-processes 1 -C 28000 -P 5432 -d nominatim /srv/nominatim/src/data.osm.pbf
The command '/bin/sh -c service postgresql start &&     sudo -u nominatim ${USERHOME}/Nominatim/build/utils/setup.php       --osm-file /srv/nominatim/src/data.osm.pbf       --all       --threads ${BUILD_THREADS}       --osm2pgsql-cache ${OSM2PGSQL_CACHE} &&     service postgresql stop' returned a non-zero code: 255

Note - We are using below machine for the same - 

RAM: 32GB
CORE: 8
STORAGE: 1TB

Build config: 
BUILD_THREADS=16
BUILD_MEMORY=26GB
OSM2PGSQL_CACHE=20000

Please let me know if you need more info.

Thanks,
  - Dev

**Comment by merlinnot** [comment]
Hi,

could you please validate that you are able to run:
```
docker build github.com/merlinnot/nominatim-docker   -t nominatim   --build-arg BUILD_THREADS=1   --build-arg BUILD_MEMORY=2GB   --build-arg OSM2PGSQL_CACHE=1000 --build-arg PBF_URL=http://download.geofabrik.de/europe/monaco-latest.osm.pbf   --build-arg REPLICATION_URL=http://download.geofabrik.de/monaco-updates
```

It shouldn't take longer than 15 minutes.

In which rank do you get an error? Could you make a [gist](https://gist.github.com) with the whole output?

**Comment by devendrasr** [comment]
Hi @merlinnot ,
I got the root cause, it was because of the instance storage getting full while importing data to postgresql. I cleaned the disk and ran the command manually in docker last night, the import is in progress as of now.

Thanks for the help!
  - Dev
